# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test application

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install netaddr==1.3.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run download.sh
      env:
        IPINFO_API_TOKEN: ${{ secrets.IPINFO_API_TOKEN }}
      run: |
        ./download.sh
    - name: Commit files
      run: |
        set -euo pipefail
        set -x
        git config --local user.email "$(git log --format='%ae' --reverse | head -1)"
        git config --local user.name "$(git log --format='%an' --reverse | head -1)"
        git add .
        if [ -z $(git status --porcelain) ]; then
            echo 'No changes'
            exit 0
        fi
        git commit -m "autocommit github workflow $(date '+%F_%R')"
        git push
